
[serve]
port = 8080

[watch]
debounce = 1000 # milliseconds
patterns = ["styles.css", "tailwind.config.js", "index.html"]
command = "npm run build:css"

[build.step]
command = "npm run build:css"

[tools]
# Default dart-sass version to download.
sass = "1.69.5"
# Default wasm-bindgen version to download.
wasm_bindgen = "0.2.95"
# Default wasm-opt version to download.
wasm_opt = "version_116"
# Default tailwindcss-cli version to download.
tailwindcss = "3.3.5"
