name: Deploy Boids Simulation

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Tailwind Dependencies
        run: npm ci

      - name: Build with Trunk and Tailwind
        run: |
          npm run build:css
          trunk build --release

      - name: Add .nojekyll
        run: echo > dist/.nojekyll

      # Step 8: Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true

