name: Deploy Boids Simulation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v2

      # Step 2: Install Rust toolchain and WebAssembly target
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      # Step 3: Cache Rust dependencies for faster builds
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1

      # Step 4: Install Trunk for building the project
      - name: Install Trunk
        uses: jetli/trunk-action@v0.1.0

      # Step 5: Install Node.js and Tailwind dependencies
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Tailwind Dependencies
        run: npm ci

      # Step 6: Build Tailwind CSS and Trunk
      - name: Build with Trunk and Tailwind
        run: |
          npm run build:css
          trunk build --release

      # Step 7: Add .nojekyll to prevent Jekyll processing
      - name: Add .nojekyll
        run: echo > dist/.nojekyll

      # Step 8: Deploy to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          single-commit: true

